mysite/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout")
]

mysite/articles/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.article_list, name="list"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('create/', views.article_create, name="create"),
   path('<int:article_id>/', views.article_detail, name="detail"),
    path('edit/<int:article_id>/', views.article_edit, name="edit"),
    

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from articles import views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
    path('', article_views.article_list, name="home"),

]

urlpatterns +=staticfiles_urlpatterns()

mysite/accounts/models.py
from django.db import models

# Create your models here.

mysite/articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
	title = models.CharField(max_length=100)
	slug = models.SlugField()
	body = models.TextField()
	date = models.DateTimeField(auto_now_add=True)
	author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
	def __str__(self):
		return self.title

	def snippet(self):
		return self.body[:50]+'...'

mysite/articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body']

mysite/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout




def signup_view(request):
    if request.method =='POST':
        form =UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()

    return render(request, 'accounts/signup.html', {'form':form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next'in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:dashboard')

            
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form':form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

mysite/articles/views.py
from django.shortcuts import render, redirect
from .models import Article 
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms


def article_list(request):
	articles = Article.objects.all().order_by('-date')
	return render(request, 'articles/article_list.html',{'articles':articles})

def dashboard(request):
	user = request.user
	articles = Article.objects.filter(author = user)
	return render(request, 'articles/dashboard.html',{'articles':articles})



def article_detail(request, article_id):
	article = Article.objects.get(id = article_id)
	return render(request, 'articles/article_detail.html', {'article': article})

@login_required(login_url="/accounts/login/")
def article_create(request):
	if request.method =='POST':
		form = forms.CreateArticle(request.POST)
		if form.is_valid():
			instance = form.save(commit=False)
			instance.author = request.user
			instance.save()
			return redirect('articles:list')
	else:
		form = forms.CreateArticle()
	return render(request, 'articles/article_create.html', {'form':form})

@login_required(login_url="/accounts/login/")
def article_edit(request, article_id):
    article = Article.objects.get(id=article_id)
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, instance=article)
        if form.is_valid():
            form.save()
            return redirect('articles:dashboard')
        else:
            form = forms.CreateArticle(instance=article)
    else:
        form = forms.CreateArticle(instance=article)
    return render(request, 'articles/article_edit.html', {'form':form , 'article':article })
	

mysite/mysite/views.py
from django.http import HttpResponse





	

mysite/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Login</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        <input type="submit" value="Login">
    </form>

{% endblock %}

mysite/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Signup</h1>
    <form class="site-form" action="/accounts/signup/" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Signup">
    </form>

{% endblock %}

mysite/articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
  	<div class="create-article">
		<h2>Create a New Article</h2>
		<form class="site-form" action="{% url 'articles:create' %}" method="post">
			{% csrf_token %}
			{{ form }}
			<input type="submit" value="Create">
		</form>	
  	</div>
 {% endblock %}
  	
 

mysite/articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
  	<div class="article_detail">
  			<div class="article">
  				<h2>{{ article.title }}</h2>
  				<p>{{ article.body }}</p>
  				<p>{{ article.date }}</p>

  			</div>
  		
  	</div>
 {% endblock %}
  	
 

mysite/articles/templates/articles/article_edit.html
{% extends 'base_layout.html' %}

{% block content %}
  	<div class="edit-article">
		<h2>Edit your Article</h2>
		<form class="site-form" action="{% url 'articles:edit' article_id=article.id %}" method="post">
            {% csrf_token %}
			{{ form }}
			<input type="submit" value="Save">
		</form>	
  	</div>
 {% endblock %}
  	
 

mysite/articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content %}
  	<h1>Article List</h1>
  	<div class="articles">
  		{% for article in articles %}
  			<div class="article">
  				<h2><a href="/articles/{{ article.id }}/">{{ article.title }}</a></h2>
  				<p>{{ article.snippet }}</p>
				<p>{{ article.date }} </p>
				<p class="author">added by {{ article.author }}</p>
				  

  			</div>
  		{% endfor %}
  		
  	</div>
 {% endblock %}
  	
 

mysite/articles/templates/articles/dashboard.html
{% extends 'base_layout.html' %}

{% block content %}
  	<h1>Your Articles </h1>
  	<div class="articles">
  		{% for article in articles %}
  			<div class="article">
  				<h2><a href="/articles/{{ article.id }}/">{{ article.title }}</a></h2>
  				<p>{{ article.snippet }}</p>
                <p>{{ article.date }} , Author- {{ article.author }}</p>
                <a href="/articles/edit/{{ article.id }}/" class="highlight">Edit</a>
                

  			</div>
  		{% endfor %}
  		
  	</div>
 {% endblock %}
  	
 

mysite/templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Blogger</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
  </head>
  <body>
    <header class="wrapper">
      <h1><a href="{% url 'home' %}"><img src="{% static 'logo.png'%}"width="250" height="50"></a></h1>
      <nav>
        <ul>
          {% if user.is_authenticated %}
            <li>
              <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                {% csrf_token %}
                <button type="submit" >Logout</button>
              </form>
            </li>
            <li>
              <a href="{% url 'articles:dashboard' %}" class="highlight">Dashboard</a>
            </li>
            <li>
              <a href="{% url 'articles:create' %}" class="highlight">Create New Article</a>
            </li>
          {% else %}
          <li>
            <a href="{% url 'accounts:login' %}" class="highlight">Login</a>
          </li>
          <li>
            <a href="{% url 'accounts:signup' %}" class="highlight">Signup</a>
          </li>
         
          {% endif %}
        </ul>
      </nav>
      

    </header>
  	<div class="wrapper">
  		{% block content%}
  		{% endblock %}
  	</div>
  	
  </body>
</html>